# Generated by Django 5.1.2 on 2024-10-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridents',
            new_name='ingredients',
        ),
    ]
